// A curated set of continents, countries, and well-known cities, used to
// keep the "place" category honest to its name. Broad rather than
// exhaustive — real gazetteers run into the millions — but wide enough that
// a stranger playing cold can find one for almost any letter, including
// common phrase-names ("new zealand", "united states") a fixed single-word
// list would otherwise wrongly reject.
const PLACES = new Set(
  [
    // continents
    "africa", "antarctica", "asia", "europe", "oceania",
    "north america", "south america",

    // countries (plus common alternate/phrase names)
    "afghanistan", "albania", "algeria", "andorra", "angola", "antigua",
    "argentina", "armenia", "australia", "austria", "azerbaijan",
    "bahamas", "bahrain", "bangladesh", "barbados", "belarus", "belgium",
    "belize", "benin", "bhutan", "bolivia", "bosnia", "botswana", "brazil",
    "brunei", "bulgaria", "burkina faso", "burundi",
    "cambodia", "cameroon", "canada", "cape verde", "chad", "chile", "china",
    "colombia", "comoros", "congo", "costa rica", "croatia", "cuba",
    "cyprus", "czechia", "czech republic",
    "denmark", "djibouti", "dominica", "dominican republic",
    "ecuador", "egypt", "el salvador", "england", "eritrea", "estonia",
    "eswatini", "ethiopia",
    "fiji", "finland", "france",
    "gabon", "gambia", "georgia", "germany", "ghana", "greece", "grenada",
    "guatemala", "guinea", "guyana",
    "haiti", "honduras", "hungary",
    "iceland", "india", "indonesia", "iran", "iraq", "ireland", "israel",
    "italy", "ivory coast",
    "jamaica", "japan", "jordan",
    "kazakhstan", "kenya", "kiribati", "kuwait", "kyrgyzstan",
    "laos", "latvia", "lebanon", "lesotho", "liberia", "libya",
    "liechtenstein", "lithuania", "luxembourg",
    "madagascar", "malawi", "malaysia", "maldives", "mali", "malta",
    "marshall islands", "mexico", "moldova", "monaco", "mongolia",
    "montenegro", "morocco", "mozambique", "myanmar",
    "namibia", "nauru", "nepal", "netherlands", "new zealand", "nicaragua",
    "niger", "nigeria", "north korea", "north macedonia", "norway",
    "oman",
    "pakistan", "palau", "panama", "papua new guinea", "paraguay", "peru",
    "philippines", "poland", "portugal",
    "qatar",
    "romania", "russia", "rwanda",
    "samoa", "san marino", "sao tome", "saudi arabia", "scotland",
    "senegal", "serbia", "seychelles", "singapore", "slovakia", "slovenia",
    "solomon islands", "somalia", "south africa", "south korea",
    "spain", "sri lanka", "sudan", "suriname", "sweden", "switzerland",
    "syria",
    "taiwan", "tajikistan", "tanzania", "thailand", "togo", "tonga",
    "trinidad", "tobago", "tunisia", "turkey", "turkmenistan", "tuvalu",
    "uganda", "ukraine", "united arab emirates", "uae", "united kingdom",
    "uk", "united states", "usa", "uruguay", "uzbekistan",
    "vanuatu", "vatican", "venezuela", "vietnam",
    "wales",
    "yemen",
    "zambia", "zimbabwe",

    // cities
    "abu dhabi", "abuja", "accra", "addis ababa", "adelaide", "algiers",
    "amman", "amsterdam", "ankara", "athens", "auckland",
    "baghdad", "bangalore", "bangkok", "barcelona", "beirut", "beijing",
    "belfast", "berlin", "birmingham", "bogota", "boston", "brasilia",
    "brisbane", "brussels", "budapest", "buenos aires", "busan",
    "cairo", "calgary", "canberra", "cape town", "capetown", "caracas",
    "casablanca", "chennai", "chicago", "colombo", "copenhagen",
    "damascus", "dakar", "delhi", "denver", "dhaka", "doha", "dubai",
    "dublin",
    "edinburgh",
    "florence", "frankfurt",
    "geneva", "glasgow", "guangzhou",
    "hanoi", "harare", "havana", "helsinki", "hollywood", "hong kong",
    "houston", "hyderabad",
    "islamabad", "istanbul",
    "jakarta", "jeddah", "johannesburg",
    "kampala", "karachi", "kathmandu", "khartoum", "kigali", "kolkata",
    "kyoto",
    "lagos", "lahore", "lima", "lisbon", "liverpool", "london",
    "los angeles", "lusaka", "lyon",
    "madrid", "manchester", "manila", "melbourne", "miami", "milan",
    "montevideo", "montreal", "moscow", "mumbai", "munich",
    "nagoya", "nairobi", "naples", "new york",
    "osaka", "oslo", "ottawa",
    "paris", "perth", "phnom penh", "prague", "pune",
    "quebec", "quito",
    "reykjavik", "riyadh", "rio de janeiro", "rome",
    "santiago", "seoul", "shanghai", "shenzhen", "singapore city",
    "stockholm", "sydney",
    "taipei", "tehran", "tel aviv", "tokyo", "toronto", "tunis",
    "vancouver", "venice", "vienna",
    "warsaw", "washington", "wuhan",
    "xiamen", "xian",
    "yangon", "yokohama", "york",
    "zurich",
  ].map((place) => place.toLowerCase()),
);

export function isKnownPlace(word: string): boolean {
  return PLACES.has(word.trim().toLowerCase());
}
