// Generates src/scripts/cities-generated.ts from the all-the-cities dataset
// (GeoNames-derived, ~135k cities with population), and
// src/scripts/states-generated.ts from iso-3166-2 (ISO 3166-2 country
// subdivisions -- states, provinces, regions). We don't ship either source
// package to the browser -- they're devDependencies used once here to
// produce plain string arrays, the same shape as places.ts's hand-curated
// list.
//
// Re-run with: node scripts/generate-places.mjs
import { writeFile } from "node:fs/promises";
import cities from "all-the-cities";
import iso31662 from "iso-3166-2";

// National-capital feature code, kept regardless of population -- several
// capitals (e.g. small island nations) fall under the population floor.
const CAPITAL_FEATURE_CODE = "PPLC";
const MIN_POPULATION = 50_000;

function stripDiacritics(word) {
  return word.normalize("NFD").replace(/[̀-ͯ]/g, "");
}

async function writeGenerated(filename, exportName, names, sourceNote) {
  const sorted = [...names].sort();
  const output = `// Generated by scripts/generate-places.mjs -- do not edit by hand.
// ${sourceNote}
// Re-run \`node scripts/generate-places.mjs\` to refresh.
export const ${exportName}: string[] = ${JSON.stringify(sorted, null, 2)};
`;
  await writeFile(new URL(`../src/scripts/${filename}`, import.meta.url), output);
  console.log(`Wrote ${sorted.length} names to src/scripts/${filename}`);
}

const cityNames = new Set();
for (const city of cities) {
  if (city.featureCode !== CAPITAL_FEATURE_CODE && city.population < MIN_POPULATION) {
    continue;
  }
  const normalized = stripDiacritics(city.name.trim().toLowerCase());
  if (normalized) cityNames.add(normalized);
}

await writeGenerated(
  "cities-generated.ts",
  "GENERATED_CITIES",
  cityNames,
  `Source: all-the-cities (GeoNames), filtered to national capitals plus
// cities with population >= ${MIN_POPULATION.toLocaleString()}, diacritics stripped so a
// plain-ASCII guess ("koln") matches the accented source name ("Köln").`,
);

const stateNames = new Set();
for (const countryCode of Object.keys(iso31662.data)) {
  const subdivisions = iso31662.data[countryCode].sub ?? {};
  for (const subdivision of Object.values(subdivisions)) {
    // Some entries carry their type as a trailing clause ("Dagestan,
    // Respublika") rather than a separate field -- the name itself is
    // everything before the first comma.
    const bareName = subdivision.name.split(",")[0];
    const normalized = stripDiacritics(bareName.trim().toLowerCase());
    if (normalized) stateNames.add(normalized);
  }
}

await writeGenerated(
  "states-generated.ts",
  "GENERATED_STATES",
  stateNames,
  `Source: iso-3166-2 (ISO 3166-2 country subdivisions -- states, provinces,
// regions, etc.), diacritics stripped and any trailing ", Type" clause
// dropped so "California" and "Dagestan" match rather than requiring the
// exact administrative label.`,
);
